# This is a basic workflow to help you get started with Actions

name: React-1stapp-surge

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install NODE
      uses: actions/setup-node@v2-beta
      with: 
        node-version: 12

    - run: npm install

    - name: Build React App
      run: CI=false npm run build
      
    - name: Install SURGE
      run: npm i -g surge
      
    - name: Upload site
      run: surge ./build http://project002react1stapp.surge.sh/ --token ${{secrets.new_token_for_1st_react_app}}
